### ISSUE TITLE
commonizeCInterop fails with `Unresolved classifier: platform/darwin/xpc_rich_error_t` on XCode 14.2

### ISSUE THREAD

**Issue by erksch** [getsentry/sentry-kotlin-multiplatform#44]
### Environment

Apple M1 Pro
XCode 14.2
macOS Ventura 13.0.1

### Steps to Reproduce

```
./gradlew build
```

### Expected Result

Builds successfully.

### Actual Result

```
> Task :sentry-kotlin-multiplatform:commonizeCInterop FAILED
Exception in thread "main" java.lang.IllegalStateException: Unresolved classifier: platform/darwin/xpc_rich_error_t
        at org.jetbrains.kotlin.commonizer.metadata.CirTypeAliasExpansion$Companion.create(CirTypeAliasExpander.kt:183)
        at org.jetbrains.kotlin.commonizer.metadata.CirDeserializers.type(CirDeserializers.kt:367)
        at org.jetbrains.kotlin.commonizer.metadata.CirDeserializers.valueParameter(CirDeserializers.kt:199)
        at org.jetbrains.kotlin.commonizer.metadata.CirDeserializers.function(CirDeserializers.kt:178)
        at org.jetbrains.kotlin.commonizer.tree.deserializer.CirTreeFunctionDeserializer.invoke(CirTreeFunctionDeserializer.kt:29)
        at org.jetbrains.kotlin.commonizer.tree.deserializer.CirTreePackageDeserializer.invoke(CirTreePackageDeserializer.kt:33)
        at org.jetbrains.kotlin.commonizer.tree.deserializer.CirTreeModuleDeserializer.invoke(CirTreeModuleDeserializer.kt:32)
        at org.jetbrains.kotlin.commonizer.tree.deserializer.RootCirTreeDeserializer.invoke(RootCirTreeDeserializer.kt:37)
 ...
```

Seems to be related to this issue: https://youtrack.jetbrains.com/issue/KT-54225/Native-update-to-Xcode-14.1

Updating Kotlin to `1.8.0` (Kotlin and Kotlin Gradle Plugin) solves this issue but creates a new one.

```
> Task :sentry-samples:kmp-app:shared:commonizeCInterop FAILED
Exception in thread "main" java.lang.IllegalStateException: Unresolved classifier: cocoapods/Sentry/SentryBreadcrumb
	at org.jetbrains.kotlin.commonizer.metadata.CirTypeAliasExpander.expandClassType(CirTypeAliasExpander.kt:216)
	at org.jetbrains.kotlin.commonizer.metadata.CirTypeAliasExpander.expandTypeProjection(CirTypeAliasExpander.kt:73)
	at org.jetbrains.kotlin.commonizer.metadata.CirTypeAliasExpander.expandClassType(CirTypeAliasExpander.kt:140)
	at org.jetbrains.kotlin.commonizer.metadata.CirTypeAliasExpander.expandTypeProjection(CirTypeAliasExpander.kt:73)
	at org.jetbrains.kotlin.commonizer.metadata.CirTypeAliasExpander.expand(CirTypeAliasExpander.kt:44)
	at org.jetbrains.kotlin.commonizer.metadata.CirDeserializers.type(CirDeserializers.kt:366)
```

Removing the samples project ultimately resolved the issue.

**Comment by LivPNavusoft** [comment]
Ran into a similar issue myself, +1 to the solution, in my case an invalidate caches and restart was required.

**Comment by buenaflor** [comment]
Hi! any build issue should be fixed. Please try it out if you can! We are also preparing a release soon so there will be no need for any local testing :)

**Comment by erksch** [comment]
@buenaflor Thanks! We are looking forward to the published version!

**Comment by buenaflor** [comment]
@erksch hope you tried it out! If you have any feedback/issues don't hesitate to reach out :)
